- hosts: localhost
  become: true
  tasks:
  - name: Install openvpn and git
    apt: name={{item}}
    with_items:
      - git
      - openvpn
  - name: Download Drone
    get_url:
      url: http://downloads.drone.io/release/darwin/amd64/drone.tar.gz
      dest: /tmp/drone.tar.gz
  - name: Unzip Drone tarball to install
    unarchive:
      src: /tmp/drone.tar.gz
      dest: /usr/local/bin
      remote_src: yes
