- hosts: localhost
  become: true
  environment:
    http_proxy: http://10.9.1.80:8080
    https_proxy: http://10.9.1.80:8080
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/packages.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/kubernetes.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/docker.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/drone.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/virtualbox.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
