- hosts: localhost
  become: true
  environment:
    http_proxy: http://10.9.1.80:8080
    https_proxy: http://10.9.1.80:8080
  vars_prompt:
    - name: 'accepted_oracle_license'
      prompt: 'Do you accept the Java 8 Oracle License?'
      default: 'n'
      private: no
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/packages.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/kubernetes.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/docker.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/drone.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/virtualbox.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/java8.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
