- hosts: localhost
  become: true
  tasks:
  - name: Install openvpn and git
    apt: name={{item}}
    with_items:
      - git
      - openvpn
  - name: Download Drone
    shell: 'curl http://downloads.drone.io/release/darwin/amd64/drone.tar.gz | tar zx'
  - name: Install Drone
    shell: 'cp drone /usr/local/bin'
    when: result|success
