- hosts: localhost
  become: true
  vars_prompt:
    - name: 'accepted_oracle_license'
      prompt: 'Do you accept the Java 8 Oracle License?'
      default: 'no'
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - debug:
        msg: 'User has ACCEPTED the Java 8 Oracle License, Java will be installed..'
      when: accepted_oracle_license == 'y' or accepted_oracle_license == 'yes'
    - debug:
        msg: 'User has NOT ACCEPTED the Java 8 Oracle License, Java will NOT be installed'
      when: accepted_oracle_license != 'y' and accepted_oracle_license != 'yes'
    - include: tasks/packages.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/kubernetes.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/docker.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/drone.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/virtualbox.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial'
    - include: tasks/java8.yml
      when: accepted_oracle_license == 'y' or accepted_oracle_license == 'yes' and (ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial')
