- name: Add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add repo to apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: Update repositories
  apt: update_cache=yes
  changed_when: False
- name: Install Docker
  apt: name=docker-ce
  allow_unauthenticated: yes
