- name: Add Java 8 repo to apt
  apt_repository:
    repo: ppa:webupd8team/java
- name: Update repositories
  apt: update_cache=yes
  changed_when: False
- name: Install Java 8
  apt: name=oracle-java8-installer
