- name: Add VirtualBox key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: Add repo to apt
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present
- name: Update repositories
  apt: update_cache=yes
  changed_when: False
- name: Install VirtualBox
  apt: name=virtualbox-5.2
