- name: Add VirtualBox key
  apt_key:
    # url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    url: http://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: Add repo to apt
  copy:
    dest: /etc/apt/sources.list.d/virtualbox.list
    content: 'deb http://download.virtualbox.org/virtualbox/debian `lsb_release -cs` contrib'
- name: Install VirtualBox
  apt: name=virtualbox-5.2
  update_cache: yes
